In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Resources/dementia_patients_health_data.csv")
df.head()


Diabetic  AlcoholLevel  HeartRate  BloodOxygenLevel  BodyTemperature  \
0         1      0.084974         98         96.230743        36.224852   
1         0      0.016973         78         93.032122        36.183874   
2         0      0.009000         89         93.566504        37.326321   
3         0      0.086437         60         93.906510        37.030620   
4         1      0.150747         67         97.508994        36.062121   

      Weight  MRI_Delay Prescription  Dosage in mg  Age  ...  Smoking_Status  \
0  57.563978  36.421028          NaN           NaN   60  ...  Current Smoker   
1  56.832335  31.157633  Galantamine          12.0   61  ...   Former Smoker   
2  59.759066  37.640435          NaN           NaN   69  ...   Former Smoker   
3  58.266471  50.673992    Donepezil          23.0   78  ...    Never Smoked   
4  67.705027  27.810601    Memantine          20.0   77  ...    Never Smoked   

    APOE_ε4  Physical_Activity Depression_Status Cognitive_Test_Scores  \
0  Negative          Sedentary                No                    10   
1  Positive  Moderate Activity                No                     1   
2  Negative  Moderate Activity                No                     8   
3  Negative      Mild Activity               Yes                     5   
4  Positive      Mild Activity                No                     0   

  Medication_History      Nutrition_Diet Sleep_Quality  \
0                 No       Low-Carb Diet          Poor   
1                Yes       Low-Carb Diet          Poor   
2                 No  Mediterranean Diet          Poor   
3                Yes       Balanced Diet          Poor   
4                Yes       Low-Carb Diet          Good   

   Chronic_Health_Conditions Dementia  
0                   Diabetes        0  
1              Heart Disease        1  
2              Heart Disease        0  
3               Hypertension        1  
4                   Diabetes        1  

[5 rows x 24 columns]

In [2]:

df = df[["Diabetic", "HeartRate", "BloodOxygenLevel", "Weight", "Age", "Smoking_Status", "Gender", "Physical_Activity", "Depression_Status", "Nutrition_Diet", "Sleep_Quality"]]
df.head()


Diabetic  HeartRate  BloodOxygenLevel     Weight  Age  Smoking_Status  \
0         1         98         96.230743  57.563978   60  Current Smoker   
1         0         78         93.032122  56.832335   61   Former Smoker   
2         0         89         93.566504  59.759066   69   Former Smoker   
3         0         60         93.906510  58.266471   78    Never Smoked   
4         1         67         97.508994  67.705027   77    Never Smoked   

   Gender  Physical_Activity Depression_Status      Nutrition_Diet  \
0  Female          Sedentary                No       Low-Carb Diet   
1    Male  Moderate Activity                No       Low-Carb Diet   
2    Male  Moderate Activity                No  Mediterranean Diet   
3  Female      Mild Activity               Yes       Balanced Diet   
4    Male      Mild Activity                No       Low-Carb Diet   

  Sleep_Quality  
0          Poor  
1          Poor  
2          Poor  
3          Poor  
4          Good

In [3]:

df.info()
df = df.dropna()
df.isnull().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Diabetic           1000 non-null   int64  
 1   HeartRate          1000 non-null   int64  
 2   BloodOxygenLevel   1000 non-null   float64
 3   Weight             1000 non-null   float64
 4   Age                1000 non-null   int64  
 5   Smoking_Status     1000 non-null   object 
 6   Gender             1000 non-null   object 
 7   Physical_Activity  1000 non-null   object 
 8   Depression_Status  1000 non-null   object 
 9   Nutrition_Diet     1000 non-null   object 
 10  Sleep_Quality      1000 non-null   object 
dtypes: float64(2), int64(3), object(6)
memory usage: 86.1+ KB


Diabetic             0
HeartRate            0
BloodOxygenLevel     0
Weight               0
Age                  0
Smoking_Status       0
Gender               0
Physical_Activity    0
Depression_Status    0
Nutrition_Diet       0
Sleep_Quality        0
dtype: int64

In [4]:

def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map


In [5]:

from sklearn.preprocessing import LabelEncoder
le_smoking = LabelEncoder()
df['Smoking_Status'] = le_smoking.fit_transform(df['Smoking_Status'])
df["Smoking_Status"].unique()
#le.classes_


array([0, 1, 2])

In [6]:

le_heartrate = LabelEncoder()
df['HeartRate'] = le_heartrate.fit_transform(df['HeartRate'])
df["HeartRate"].unique()


array([38, 18, 29,  0,  7, 34, 30,  9,  4, 37, 33, 31, 35, 24, 14, 22, 16,
       39, 17,  6, 27, 15, 28, 23, 11, 10, 36,  1, 20, 25,  3, 12,  5, 13,
       19,  8,  2, 21, 32, 40, 26])

In [7]:

le_bloodoxygen = LabelEncoder()
df['BloodOxygenLevel'] = le_bloodoxygen.fit_transform(df['BloodOxygenLevel'])
df["BloodOxygenLevel"].unique()


array([591, 261, 328, 364, 718, 424, 606, 189, 979,  38, 187, 641, 876,
       699, 343, 682, 971, 623, 303, 498, 358, 122, 922, 280, 963, 258,
       346, 907,  50, 748, 123, 573,  30, 217, 890,  33, 597, 609, 670,
       580, 866, 554,   3,  23, 119, 168, 136, 317, 818, 219, 880, 507,
       376, 885,  47, 798, 587, 603,  54, 295, 540, 594, 884, 537, 422,
       531, 161, 468, 518, 746, 741, 949, 221, 170, 284, 350, 238, 538,
       781,  85, 405, 800, 159, 323, 671,   8, 478, 788, 902, 844, 402,
       874, 371, 898, 959,  94, 871, 484, 361, 903, 349, 320, 577,  46,
       178, 289, 319,  39, 786, 900, 765, 299, 108, 535, 264, 799, 947,
        79,  36, 845, 333, 601, 910,  73, 708, 783, 712, 347, 975, 100,
       496, 590, 304, 802, 766, 690, 556, 561, 266, 747, 886, 981, 568,
       511, 400, 883, 621, 363, 574, 160, 846, 545, 943, 605, 214, 896,
       704, 643, 856, 125, 509, 711,  63, 362, 752, 382, 378,  69, 499,
       523, 373, 957, 909,  43, 325, 413, 563, 263, 420, 510, 89

In [8]:

le_weight = LabelEncoder()
df['Weight'] = le_weight.fit_transform(df['Weight'])
df["Weight"].unique()


array([167, 156, 218, 180, 364, 346, 681, 405,  84, 182, 637, 560, 151,
       198,  95, 471, 102, 868, 341, 704, 130, 696, 518, 458, 308, 610,
       398,  16, 300,  87, 907, 690, 352, 295, 541, 996, 588, 718, 274,
       148, 347, 568,  98, 501, 382, 605, 377, 717, 798, 271, 558, 584,
       124,  59, 975,  13, 142, 530, 670,  28,  10, 843, 379, 550,  60,
       440, 165, 969, 212, 187, 189, 469, 994, 641, 288, 338, 779, 845,
       492, 113, 626, 931, 631, 340, 745, 462, 985, 663, 945, 678, 974,
       438, 229, 171, 748, 515, 309,  25, 758, 970,  30, 239, 715, 875,
       279, 294, 714,  75,  37, 697, 832,  41, 473, 983, 133, 441, 394,
       824, 495, 890, 821, 577, 859, 545, 944, 831, 276, 581, 158,  91,
       968, 210, 760, 298, 830, 918, 362, 254, 409, 207, 949, 536, 930,
       483, 114, 902, 816, 200,  63, 684, 775, 813, 655, 426, 122, 491,
       928, 679, 842, 514, 976, 987, 205, 960,  21, 889, 498, 235, 499,
       245, 709, 186, 846,  55, 919, 146, 891, 439, 674, 195,  8

In [9]:

le_age = LabelEncoder()
df['Age'] = le_age.fit_transform(df['Age'])
df["Age"].unique()


array([ 0,  1,  9, 18, 17,  7, 27,  6, 13, 16,  4, 30, 29, 12, 25, 10, 15,
       11, 28,  3, 23, 14, 19,  5,  2, 22, 24,  8, 21, 20, 26])

In [10]:

le_gender = LabelEncoder()
df['Gender'] = le_gender.fit_transform(df['Gender'])
df["Gender"].unique()


array([0, 1])

In [11]:

le_physicalact = LabelEncoder()
df['Physical_Activity'] = le_gender.fit_transform(df['Physical_Activity'])
df["Physical_Activity"].unique()


array([2, 1, 0])

In [12]:

le_depression = LabelEncoder()
df['Depression_Status'] = le_depression.fit_transform(df['Depression_Status'])
df["Depression_Status"].unique()


array([0, 1])

In [13]:

le_nutrition = LabelEncoder()
df['Nutrition_Diet'] = le_nutrition.fit_transform(df['Nutrition_Diet'])
df["Nutrition_Diet"].unique()


array([1, 2, 0])

In [14]:

le_sleep = LabelEncoder()
df['Sleep_Quality'] = le_sleep.fit_transform(df['Sleep_Quality'])
df["Sleep_Quality"].unique()


array([1, 0])

In [15]:

X = df.drop("Diabetic", axis=1)
y = df["Diabetic"]


In [16]:

from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)


LinearRegression()

In [17]:

y_pred = linear_reg.predict(X)


In [18]:

from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))


In [19]:

error


0.4987339475706293

In [20]:

from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)


DecisionTreeRegressor(random_state=0)

In [21]:

y_pred = dec_tree_reg.predict(X)


In [22]:

error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))


0.00


In [23]:

from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)


RandomForestRegressor(random_state=0)

In [24]:
y_pred = random_forest_reg.predict(X)


In [25]:
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))

0.19


In [26]:


from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)



GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [27]:




regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))



0.50


In [28]:


X



HeartRate  BloodOxygenLevel  Weight  Age  Smoking_Status  Gender  \
0           38               591     167    0               0       0   
1           18               261     156    1               1       1   
2           29               328     218    9               1       1   
3            0               364     180   18               2       0   
4            7               718     364   17               2       1   
..         ...               ...     ...  ...             ...     ...   
995         27               357       8   28               2       1   
996         37               421     899   20               2       0   
997          5               833     607    7               2       0   
998         11               131     927    2               2       1   
999         30               513     170   20               2       0   

     Physical_Activity  Depression_Status  Nutrition_Diet  Sleep_Quality  
0                    2                  0               1              1  
1                    1                  0               1              1  
2                    1                  0               2              1  
3                    0                  1               0              1  
4                    0                  0               1              0  
..                 ...                ...             ...            ...  
995                  0                  0               0              1  
996                  1                  0               1              1  
997                  2                  0               0              0  
998                  2                  1               1              0  
999                  0                  0               2              0  

[1000 rows x 10 columns]

In [29]:



X_1 = np.array([[98, 96.23, 57.56, 60, 'Current Smoker', 'Female', 'Sedentary', 'No', 'Low-Carb Diet', 'Poor']])
X_1


array([['98', '96.23', '57.56', '60', 'Current Smoker', 'Female',
        'Sedentary', 'No', 'Low-Carb Diet', 'Poor']], dtype='<U32')

In [33]:
# Concatenate training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_combined = pd.concat([X_train, X_test])

# Fit the LabelEncoders on the combined dataset
le_heartrate.fit(X_combined.iloc[:, 0])
le_bloodoxygen.fit(X_combined.iloc[:, 1])
le_weight.fit(X_combined.iloc[:, 2])
le_age.fit(X_combined.iloc[:, 3])
le_smoking.fit(X_combined.iloc[:, 4])
le_gender.fit(X_combined.iloc[:, 5])
le_physicalact.fit(X_combined.iloc[:, 6])
le_depression.fit(X_combined.iloc[:, 7])
le_nutrition.fit(X_combined.iloc[:, 8])
le_sleep.fit(X_combined.iloc[:, 9])

# Transform the features using LabelEncoders
X.iloc[:, 0] = le_heartrate.transform(X.iloc[:, 0])
X.iloc[:, 1] = le_bloodoxygen.transform(X.iloc[:, 1])
X.iloc[:, 2] = le_weight.transform(X.iloc[:, 2])
X.iloc[:, 3] = le_age.transform(X.iloc[:, 3])
X.iloc[:, 4] = le_smoking.transform(X.iloc[:, 4])
X.iloc[:, 5] = le_gender.transform(X.iloc[:, 5])
X.iloc[:, 6] = le_physicalact.transform(X.iloc[:, 6])
X.iloc[:, 7] = le_depression.transform(X.iloc[:, 7])
X.iloc[:, 8] = le_nutrition.transform(X.iloc[:, 8])
X.iloc[:, 9] = le_sleep.transform(X.iloc[:, 9])

# Convert X to float
X = X.astype(float)


In [34]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Shape of X: (1000, 10)
Shape of y: (1000,)


In [35]:




y_pred = regressor.predict(X)
y_pred



array([0.47609562, 0.47609562, 0.47609562, 0.47609562, 0.53594771,
       0.47609562, 0.47609562, 0.47609562, 0.47609562, 0.53594771,
       0.53594771, 0.53594771, 0.47609562, 0.53594771, 0.65625   ,
       0.53594771, 0.53594771, 0.47609562, 0.47609562, 0.53594771,
       0.47609562, 0.47609562, 0.47609562, 0.53594771, 0.47609562,
       0.53594771, 0.47609562, 0.47609562, 0.53594771, 0.47609562,
       0.47609562, 0.47609562, 0.53594771, 0.47609562, 0.53594771,
       0.47609562, 0.53594771, 0.53594771, 0.47609562, 0.53594771,
       0.53594771, 0.47609562, 1.        , 0.47609562, 0.47609562,
       0.47609562, 0.47609562, 0.47609562, 0.53594771, 0.53594771,
       0.53594771, 0.53594771, 0.53594771, 0.53594771, 0.53594771,
       0.53594771, 0.47609562, 0.53594771, 0.47609562, 0.47609562,
       0.53594771, 0.53594771, 0.53594771, 0.53594771, 0.47609562,
       0.47609562, 0.47609562, 0.65625   , 0.47609562, 0.47609562,
       0.53594771, 0.53594771, 0.53594771, 0.53594771, 0.47609

In [36]:



import pickle



In [38]:
data = {"model": regressor, "le_heartrate": le_heartrate, "le_bloodoxygen": le_bloodoxygen, "le_weight": le_weight, "le_age": le_age, "le_smoking": le_smoking, "le_gender": le_gender, "le_physicalact": le_physicalact, "le_depression": le_depression, "le_nutrition": le_nutrition, "le_sleep": le_sleep}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_heartrate = data["le_heartrate"]
le_bloodoxygen = data["le_bloodoxygen"]
le_weight = data["le_weight"]
le_age = data["le_age"] 
le_smoking = data["le_smoking"]
le_gender = data["le_gender"]
le_physicalact = data["le_physicalact"]
le_depression = data["le_depression"] 
le_nutrition = data["le_nutrition"] 
le_sleep = data["le_sleep"] 


In [39]:

y_pred = regressor_loaded.predict(X)
y_pred
 


array([0.47609562, 0.47609562, 0.47609562, 0.47609562, 0.53594771,
       0.47609562, 0.47609562, 0.47609562, 0.47609562, 0.53594771,
       0.53594771, 0.53594771, 0.47609562, 0.53594771, 0.65625   ,
       0.53594771, 0.53594771, 0.47609562, 0.47609562, 0.53594771,
       0.47609562, 0.47609562, 0.47609562, 0.53594771, 0.47609562,
       0.53594771, 0.47609562, 0.47609562, 0.53594771, 0.47609562,
       0.47609562, 0.47609562, 0.53594771, 0.47609562, 0.53594771,
       0.47609562, 0.53594771, 0.53594771, 0.47609562, 0.53594771,
       0.53594771, 0.47609562, 1.        , 0.47609562, 0.47609562,
       0.47609562, 0.47609562, 0.47609562, 0.53594771, 0.53594771,
       0.53594771, 0.53594771, 0.53594771, 0.53594771, 0.53594771,
       0.53594771, 0.47609562, 0.53594771, 0.47609562, 0.47609562,
       0.53594771, 0.53594771, 0.53594771, 0.53594771, 0.47609562,
       0.47609562, 0.47609562, 0.65625   , 0.47609562, 0.47609562,
       0.53594771, 0.53594771, 0.53594771, 0.53594771, 0.47609